version: "3.3"
services:
  php:
    container_name: symfony_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/symfony_app
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  nginx:
    container_name: symfony_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/symfony_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  dbdata:
    driver: local

