controllers:
    resource:
        path: ../src/Segment/Infrastructure/Controller
        namespace: App\Segment\Infrastructure\Controller
    type: attribute
    prefix: /api #not working

segments:
    path: /api/avail
    controller: App\Segment\Infrastructure\Controller\GetSegmentCollectionController
    methods: GET